 - name: Настройка MySQL
 # Вы можете указать конкретный коммит или версию. 
 # использует: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
 использует: mirromutth/mysql-action@v1.1
 с:
 # Порт хоста
 порт хоста: # необязательно, по умолчанию 3306
 # Порт контейнера
 container port: # необязательно, по умолчанию 3306
 # --character-set-server — набор символов сервера MySQL
 character set server: # необязательно, по умолчанию utf8mb4
 # --collation-server — сопоставление символов сервера MySQL
 collation server: # необязательно, по умолчанию utf8mb4_general_ci
 # Используемая версия MySQL
 mysql version: # необязательно, по умолчанию последняя версия
 # MYSQL_ROOT_PASSWORD — пароль суперпользователя root
 пароль root для mysql: # необязательно, по умолчанию 
 # MYSQL_DATABASE — имя создаваемой базы данных по умолчанию
 база данных mysql: # необязательно, по умолчанию 
 # MYSQL_USER — создание указанного пользователя с правами суперпользователя для созданной базы данных
 пользователь mysql: # необязательно, по умолчанию 
 # MYSQL_PASSWORD — указанный пароль суперпользователя, который предоставляет пользователю права для созданной базы данных
 пароль mysql: # необязательно, по умолчанию 
 
 - name: Отправка зависимостей Go
 uses: actions/go-dependency-submission@v2.0.3
 with:
 # Персональный токен доступа GitHub (PAT). По умолчанию используется PAT, предоставленный исполнителем действия.
 token: # необязательно, по умолчанию используется ${{ github.token }}
 # Предоставленная пользователем карта с максимальным количеством пар «ключ-значение» метаданных, которые нужно включить в снимок, например {"lastModified": "12-31-2022"}
 metadata: # необязательно
 # Путь к репозиторию для файла go.mod, используемого для определения зависимостей для цели сборки Go.  По умолчанию используется файл go.mod в корне репозитория. 
 go-mod-path: # по умолчанию go.mod
 # Цель сборки для определения зависимостей сборки.  Если не указано, используется значение "all", при котором будут обнаружены все зависимости, используемые во всех целях сборки (включая тесты и инструменты). 
 go-build-target: # по умолчанию all
